### ISSUE TITLE
H264 playback on Firefox doesn't work after codecs bundle install and reboot

### ISSUE THREAD

**Issue by worldofgeese** [clearfraction/distribution#28] opened 2023-04-02 13:47 UTC
```sh
cat /etc/profile.d/10-cf.sh
[[ ! ${PATH} =~ "/opt/3rd-party/bundles/clearfraction/bin" ]] && \
  PATH=$PATH:/opt/3rd-party/bundles/clearfraction/bin:/opt/3rd-party/bundles/clearfraction/usr/bin:/opt/3rd-party/bundles/clearfraction/usr/local/bin

[[ ! ${LD_LIBRARY_PATH} =~ "/opt/3rd-party/bundles/clearfraction/usr/lib64" ]] && \
  LD_LIBRARY_PATH=/usr/lib64:/opt/3rd-party/bundles/clearfraction/usr/lib64:/opt/3rd-party/bundles/clearfraction/usr/local/lib64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

[[ ! ${XDG_DATA_DIRS} =~ "/opt/3rd-party/bundles/clearfraction/usr/share" ]] && \
  XDG_DATA_DIRS=${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}:/opt/3rd-party/bundles/clearfraction/usr/share/:/opt/3rd-party/bundles/clearfraction/usr/local/share/

[[ ! ${XDG_CONFIG_DIRS} =~ "/opt/3rd-party/bundles/clearfraction/usr/share/xdg" ]] && \
  XDG_CONFIG_DIRS=${XDG_CONFIG_DIRS:-/usr/share/xdg:/etc/xdg}:/opt/3rd-party/bundles/clearfraction/usr/share/xdg:/opt/3rd-party/bundles/clearfraction/etc/xdg

[[ ! ${FONTCONFIG_PATH} =~ "/usr/share/defaults/fonts" ]] && \
  FONTCONFIG_PATH=/usr/share/defaults/fonts${FONTCONFIG_PATH:+:$FONTCONFIG_PATH}

[[ ! ${GST_PLUGIN_PATH_1_0} =~ "/opt/3rd-party/bundles/clearfraction/usr/lib64/gstreamer-1.0" ]] && \
  GST_PLUGIN_PATH_1_0=${GST_PLUGIN_PATH_1_0:-/usr/lib64/gstreamer-1.0}:/opt/3rd-party/bundles/clearfraction/usr/lib64/gstreamer-1.0

```

```sh
cat /etc/environment.d/10-cf.conf
PATH=$PATH:/opt/3rd-party/bundles/clearfraction/bin:/opt/3rd-party/bundles/clearfraction/usr/bin:/opt/3rd-party/bundles/clearfraction/usr/local/bin
LD_LIBRARY_PATH=/usr/lib64:/opt/3rd-party/bundles/clearfraction/usr/lib64:/opt/3rd-party/bundles/clearfraction/usr/local/lib64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
XDG_DATA_DIRS=${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}:/opt/3rd-party/bundles/clearfraction/usr/share/:/opt/3rd-party/bundles/clearfraction/usr/local/share/
XDG_CONFIG_DIRS=${XDG_CONFIG_DIRS:-/usr/share/xdg:/etc/xdg}:/opt/3rd-party/bundles/clearfraction/usr/share/xdg:/opt/3rd-party/bundles/clearfraction/etc/xdg
FONTCONFIG_PATH=/usr/share/defaults/fonts${FONTCONFIG_PATH:+:$FONTCONFIG_PATH}
GST_PLUGIN_PATH_1_0=${GST_PLUGIN_PATH_1_0:-/usr/lib64/gstreamer-1.0}:/opt/3rd-party/bundles/clearfraction/usr/lib64/gstreamer-1.0
```

Steps I've taken:

```
sudo swupd 3rd-party add clearfraction https://download.clearfraction.cf/update
sudo swupd 3rd-party bundle-add codecs
echo "export LD_LIBRARY_PATH=/opt/3rd-party/bundles/clearfraction/usr/lib64" >> "${HOME}/.config/firefox.conf"
```

I've rebooted my machine twice and done a full profile wipe then repeated the steps above.

11th Gen Intel® Core™ i5-1135G7, GNOME on X11

**Comment by marioroy** [comment] 2023-04-03 00:21
@worldofgeese. I had success with video HW acceleration on an Intel NUC. The codecs bundle will not do it alone. You need the Firefox config and some settings via about:config.

See the [HWAccel](https://github.com/marioroy/nvidia-driver-on-clear-linux/tree/main/HWAccel) folder. Optionally, adjust the AV1 setting matching your Intel graphics AV1 capability { false or true }.

1. Install codecs bundles from 3rd-party which you have
2. Copy the firefox/firefox.conf to ~/.config/
3. Apply the following Firefox settings via about:config
a. media.ffmpeg.vaapi.enabled    true
b. media.ffvpx.enabled    false
c. media.av1.enabled    false

**Comment by paulcarroty** [comment] 2023-04-05 07:04
Tested on 38370 and it works. Thx @marioroy! README was updated.

**Comment by marioroy** [comment] 2023-04-05 08:28
There's another about:config setting for NVIDIA graphics. Basically, all the ones mentioned above including this one.

```text
Required, for HW acceleration to work using NVIDIA driver 470 (or newer series).
widget.dmabuf.force-enabled                    true
```

**Comment by worldofgeese** [comment] 2023-04-05 09:57
My experience is this still isn't working

I've applied @marioroy's changes by copying `firefox/firefox.conf` to `$HOME/.config/firefox/firefox.conf`. 

The following flags are set to true:

a. media.ffmpeg.vaapi.enabled true
b. media.ffvpx.enabled false
c. media.av1.enabled false

I'm testing with the enhanced-h264ify extension set to h264 and receive this error on YouTube

![image](https://user-images.githubusercontent.com/59834693/230046528-9978abd1-6f9c-4db7-bab8-df12e67422fe.png)

The Fedora team has put out these tips which I've confirmed are all set appropriately

![image](https://user-images.githubusercontent.com/59834693/230047265-2d16ce1e-560a-4f5b-8e6a-3f1f904bd21e.png)

![image](https://user-images.githubusercontent.com/59834693/230047479-6987411a-44e4-4bf2-b2a0-943ad720c40f.png)

Output of `vainfo`

```
Trying display: wayland
libva info: VA-API version 1.18.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_18
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.18 (libva 2.18.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.5 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileHEVCMain12             :	VAEntrypointVLD
      VAProfileHEVCMain12             :	VAEntrypointEncSlice
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain422_10         :	VAEntrypointEncSlice
      VAProfileHEVCMain422_12         :	VAEntrypointVLD
      VAProfileHEVCMain422_12         :	VAEntrypointEncSlice
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          :	VAEntrypointVLD
      VAProfileHEVCSccMain10          :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         :	VAEntrypointVLD
      VAProfileHEVCSccMain444         :	VAEntrypointEncSliceLP
      VAProfileAV1Profile0            :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointEncSliceLP
```

**Comment by paulcarroty** [comment] 2023-04-05 11:39
1. Does `ffplay https://www.w3schools.com/html/mov_bbb.mp4` works in terminal?
2. Open this [link](https://www.w3schools.com/html/html5_video.asp) in Firefox without any extensions and test the video again.

**Comment by worldofgeese** [comment] 2023-04-05 12:09
@paulcarroty both of those worked!

**Comment by x-sublime** [comment] 2023-04-05 18:11
If I try to open  mp4 , streaming or from my disk, firefox give me this error:

firefox
[Child 112732, MediaDecoderStateMachine #1] WARNING: Decoder=558b1082a400 Decode error: NS_ERROR_DOM_MEDIA_DECODE_ERR (0x806e0004) - virtual mozilla::MediaResult mozilla::FFmpegVideoDecoder<58>::DoDecode(mozilla::MediaRawData *, uint8_t *, int, bool *, MediaDataDecoder::DecodedData &): avcodec_send_packet error: Invalid argument: file /builds/worker/checkouts/gecko/dom/media/MediaDecoderStateMachineBase.cpp:164
[Child 112732, MediaDecoderStateMachine #1] WARNING: Decoder=558b1082a400 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - Error no decoder found for audio/mp4a-latm: file /builds/worker/checkouts/gecko/dom/media/MediaDecoderStateMachineBase.cpp:164

ffplay or mpv work fine with the same link or file from disk
This happens after update 3rd-Party Repository: clearfraction to vs. 38680 and I have not  h264ify extension. 
The problem seems: "Error no decoder found for audio/mp4a-latm" (ffmpeg)

 sudo swupd 3rd-party bundle-list
Password: 
_____________________________________
 3rd-Party Repository: clearfraction
_____________________________________

Installed bundles:
 - codecs-cuda
 - os-core
 - yt-dlp

Total: 3

**Comment by paulcarroty** [comment] 2023-04-05 20:10
Hmm, it's getting more interesting. Can you test the `codecs` bundle too?

Maybe [Update to 111.0.1](https://github.com/clearlinux-pkgs/firefox/commit/81e2f4dae25f89e0a88863e6e0fd6c1327e89378) did it or [ffmpeg-cuda v6 bump](https://github.com/clearfraction/ffmpeg-cuda/commit/cabfa9e6a62a1cda78e5cb3de3cd4d95156ce18e).

**Comment by x-sublime** [comment] 2023-04-05 20:29
With codecs bundle trying to open the link https://www.w3schools.com/html/mov_bbb.mp4 I get the same error:

firefox
[Child 17050, MediaDecoderStateMachine #1] WARNING: Decoder=55e1d5058500 Decode error: NS_ERROR_DOM_MEDIA_DECODE_ERR (0x806e0004) - virtual mozilla::MediaResult mozilla::FFmpegVideoDecoder<58>::DoDecode(mozilla::MediaRawData *, uint8_t *, int, bool *, MediaDataDecoder::DecodedData &): avcodec_send_packet error: Invalid argument: file /builds/worker/checkouts/gecko/dom/media/MediaDecoderStateMachineBase.cpp:164
[Child 17050, MediaDecoderStateMachine #1] WARNING: Decoder=55e1d5058500 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - Error no decoder found for audio/mp4a-latm: file /builds/worker/checkouts/gecko/dom/media/MediaDecoderStateMachineBase.cpp:164

**Comment by x-sublime** [comment] 2023-04-05 20:58
I had firefox  111.0.1 with v.38320 and all worked... probably ffmpeg v6 problem.

**Comment by marioroy** [comment] 2023-04-05 20:59
I can confirm h264 playback via 3rd-party Clear Fraction release 38320 working.  CF 38680 is not working. Firefox states Video can't be played because the file is corrupt, which is not the case as the video plays fine using CF 38320.

See also reddit thread:
https://www.reddit.com/r/firefox/comments/11x996w/firefox_110111_having_troubles_with_ffmpeg_60/

**Comment by marioroy** [comment] 2023-04-05 21:26
Firefox developers added FFmpeg 6.0 support to upcoming 112 release, scheduled for 2023-04-11.
https://wiki.mozilla.org/Release_Management/Calendar

**Comment by marioroy** [comment] 2023-04-05 21:36
Optional: How to get Firefox working now using current CF release 38680 or wait for Firefox 112. I tried the following steps and confirm Firefox 112 working with CF 38680.

```bash
1. quit Firefox
2. mv .firefox .firefox.111
3. wget https://download-installer.cdn.mozilla.net/pub/firefox/releases/112.0b9/linux-x86_64/en-US/firefox-112.0b9.tar.bz2
4. tar xjf firefox-112.0b9.tar.bz2
5. mv firefox .firefox
```

**Comment by marioroy** [comment] 2023-04-05 21:59
Often, we think that all is okay, but may forget to check if the HW video engine is used, which is what folks prefer.

1. CF codecs bundle: Folks using Intel Graphics "need" the enhanced-h264ify extension in order to decode using the HW video engine.

2. CF codecs-cuda bundle: Folks using NVIDIA graphics "do not" require the enhanced-h264ify extension to use the video engine, which is what I have. Folks may need to toggle the AV1 about:config setting depending on whether their NVIDIA graphics support it. Today, I forced Firefox to playback h264 codec by installing the enhanced-h264ify extension.

**Comment by paulcarroty** [comment] 2023-04-07 06:20
https://bugzilla.mozilla.org/show_bug.cgi?id=1819374, fixed in Firefox 112.

Workarounds: update to Firefox Beta or use `mpv + yt-dlp` for HTML5 video.

**Comment by marioroy** [comment] 2023-04-10 18:33
Firefox 112.0 is out.

https://ftp.mozilla.org/pub/firefox/releases/112.0/linux-x86_64/

Folks who did the Firefox beta workaround on Clear Linux may want to update to the release version to put Firefox back on the release track.

1. Obtain firefox-112.0.tar.bz2
2. Quit Firefox
3. cd ~
4. rm -fr .firefox
5. tar xjf ~/Downloads/firefox-112.0.tar.bz2
6. mv firefox .firefox

**Closed** 2023-04-11 15:06 UTC
